<!DOCTYPE html>
<html lang="en">
<head>
<style>

@page {
  size: A4;
  margin: 5;
}

@media print {
  html, body {
    /*width: 265mm;*/
    height: 250mm;
    border: solid 2px;
  }/* ... the rest of the rules ... */
}

.documento_bordes{
    padding: 100px 30px 5px 30px;/* 150px */
    font-size: 12px;

  }
  .documento_superior{
    height: 100px;

  }
  .documento_espacios_persona {
    padding-top: 5px;
    padding-left: 115px;
    text-align:left;
  }
  .documento_fecha_espacios{
    padding-left: 70%;
  }
  .documento_row_cantidad{
    width: 120px;
    padding-left: 90px;
    padding-top: 5px;
  }
  .documento_row_descripcion{
    width: 1200px;
    padding-left: 9px;
    padding-top: 5px;
  }
  .documento_row_pu{
    width: 130px;
    padding-left: 9px;
    padding-top: 5px;
  }
  .documento_espacios_tabla {
    padding-top: 10px;
    width: 100%;
  }

body{
  border:solid 0px red;
}
</style>
 <link rel='stylesheet' type='text/css' href='css/style.css' />
</head>
<body>

<body class="documento_bordes">

        <table cellpadding="0" cellspacing="0" border="1" style="width:100%;letter-spacing: 3pt;">
            <?php

                foreach ((array)$cliente->data as $row)
                  {
                    $mes     = $row->mes;
                    $dia     = $row->dia;
                    $anio    = $row->anio;
                    $nombrecliente = $row->nomcompleto;
                    $direccion =  $row->domiciper;
                    $dni       = $row->numdocper;
                    $ruc       = $row->numrucper;
                    $formapago  =$row->formapago;
                    $numeroguia  =$row->numeroguia;

                  }

            ?>
            <tr class="top">
                <td colspan="4" class="documento_fecha_espacios" >
                    <table border="0"  >
                        <tr>
                            <td style="width:100px;height: 30px;text-align:center;">
                             <?php echo $dia; ?>
                            </td>
                            <td style="width:100px;text-align:center;">
                            <?php echo $mes; ?>
                            </td>
                            <td style="width:70px;text-align:right;">
                            <?php echo $anio; ?>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>

            <tr >
                <td >
                    <table border="0" style="width:100%;" >

                              <tr>
                                  <td class="documento_espacios_persona" colpspand="2">
                                    <?php echo  $nombrecliente;  ?>
                                  </td>
                              </tr>
                              <tr>
                                  <td class="documento_espacios_persona">
                                  <?php echo  $direccion;  ?>
                                 </td>
                                 <td class="documento_espacios_persona" style="text-align:right" >
                                  <?php
                                  if($dni==''){
                                    echo $ruc;
                                  }else{
                                    echo   $dni;
                                  }

                                  ?>
                                 </td>

                              </tr>

                            </tr>

                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                  <td style="height:20px;"></td>
            </tr>
            <tr>
            <td>
                    <table border="0" style="width:100%;font-size:10px;">
                    <?php
                          $item=0;
                          $total=0;
                          foreach ((array)$detalle->data as $row)
                            { ?>
                                <tr>
                                  <td style="width:60px;text-align:center;height:25px;"><?php echo number_format($row->cantidad, 2, '.', ' ');   ?></td>
                                  <td style="width:200px;text-align:left;height:25px;"><?php echo $row->producto;  ?></td>
                                  <td style="width:50px;text-align:center;border:0px solid;height:25px;"><?php echo number_format($row->precio, 2, '.', ' ');  ?></td>
                                  <td style="width:50px;text-align:right;padding-right:10px;border:0px solid;height:25px;"><?php echo number_format($row->total, 2, '.', ' ');  ?></td>
                                </tr>

                          <?php
                            $total = $total + $row->total;
                            $item = $item+1;
                            }

                            if($item < 17){
                                for($i=$item;$i<17;$i++){
                            ?>
                                <tr>
                                  <td style="width:60px;text-align:center;height:25px;"> </td>
                                  <td style="width:200px;text-align:left;height:25px;"> </td>
                                  <td style="width:50px;text-align:center;border:0px solid;height:25px;"> </td>
                                  <td style="width:50px;text-align:right;padding-right:10px;border:0px solid;height:25px;"> </td>
                                </tr>

                            <?php
                                  $item = $item + 1;
                                }
                            }

                            if($item == 17){ ?>
                                <tr>
                                  <td style="width:60px;text-align:center;height:25px;"> </td>
                                  <td style="width:200px;text-align:left;height:25px;"> </td>
                                  <td style="width:50px;text-align:center;border:0px solid;height:25px;"> </td>
                                  <td style="width:50px;text-align:right;padding-right:10px;border:0px solid;height:25px;font-size:13px;"><?php echo number_format($total,2,'.',' '); ?> </td>
                                </tr>
                            <?php
                            }
                            ?>
                   </table>
            </td>
            </tr>
        </table>
    </body>
</html>

<script>
  /* jsPrintSetup.setOption('orientation', jsPrintSetup.kPortraitOrientation);
   jsPrintSetup.setOption('marginTop', 5);
   jsPrintSetup.setOption('marginBottom', 5);
   jsPrintSetup.setOption('marginLeft', 5);
   jsPrintSetup.setOption('marginRight', 5);*/
   // set page header
   //jsPrintSetup.setOption('headerStrLeft', 'Molino Avila');
   //jsPrintSetup.setOption('headerStrCenter', '');
   //jsPrintSetup.setOption('headerStrRight', '&PT');
   // set empty page footer
   //jsPrintSetup.setOption('footerStrLeft', '');
   //jsPrintSetup.setOption('footerStrCenter', '');
   //jsPrintSetup.setOption('footerStrRight', '');

   // clears user preferences always silent print value
   // to enable using 'printSilent' option
   jsPrintSetup.clearSilentPrint();
   jsPrintSetup.setOption('printSilent', 1);
   jsPrintSetup.print();
</script>
